### ISSUE TITLE
how to build complex condition

### ISSUE THREAD

**Issue by zhongv** [evrete/evrete#18]
how to build complex condition,  for example,  And  Or combine ,Maybe like MyBatis where condition

**Comment by andbi** [comment]
The library treats string conditions as Java boolean expressions, so `||`, `&&`, `!`,  `==`, ...  are all valid symbols inside `@Where` annotations. Multiple `@Where` conditions are AND-ed together.

**Comment by hongv** [comment]
yes, whether or not to plan to add lambda where condition like below

`.where('')
            .and(wp -> wp.ne(Student::getName, "1"))
            .or(
                wp ->
                    wp.eq(Student::getName, "1")
                        .and(wpp -> wpp.isNull(Student::getAge).or().ge(Student::getAge, 11)))`

**Comment by andbi** [comment]
Great idea. The problem here is that we would need to statically import a "condition builder", and then the example wouldn't be that concise:
`import static xxxx.Builder.cond;`
`import static xxxx.Builder.empty;`

`.where(empty()) .and(cond('$a > 3')) .or( cond('$b<5') .and(cond('xxx').or().cond('yyy')))`

On the other hand, that would incite developers to split conditions, which is better performance-wise.
I'm for it.

**Comment by zhongv** [comment]
agree with you,  in my mind ,it is clear more.

about import static sentence , other way can use 'Consumer' like 
`and(c->c.cond('xxx'))` 

to hide the  code, and also can open the implements to add more expression in 'Consumer'
