### ISSUE TITLE
How to compare field with string literal

### ISSUE THREAD

**Issue by hebrd** [evrete/evrete#48]
I have a where expression like 
```
"$o.account == LONG_CFD "
```

Triggering the rule resulted in:

```
java.lang.RuntimeException: org.evrete.runtime.compiler.CompilationException: Compilation error:Compilation error(s): JavaSource:org.evrete.spi.minimal.compiled.Condition3:16: error: cannot find symbol
        return var0 == LONG_CFD ;
                       ^
  symbol:   variable LONG_CFD
  location: class org.evrete.spi.minimal.compiled.Condition3
```

I also want to know that how to define customer field by method (because not corresponding field exits in the model, and I need some calculation to get the final field value)

**Comment by andbi** [comment]
The engine turns every literal condition into a Java source and then compiles it. In your case, the Java source looks something like 
```java
package org.evrete.spi.minimal.compiled;

import org.evrete.spi.minimal.ConditionBaseClass;
// other imports

class Condition3 extends ConditionBaseClass {

  public static boolean test(long var0) {
    return var0 == LONG_CFD;
  }
}
```
The `long var0` method argument stems from fact that somewhere in your rule you declared a type `$o` that has a `long` field or property named `account`. 

If you try to compile the above source, the compilation will fail with exactly the same error, because the `LONG_CFD` symbol is unknown, it's neither imported nor declared in the condition's super class.

There are two ways of making the engine aware of your constants:

1. Use the `addImport(com.abc.MyConstants.class)` method on your knowledge instance and rewrite the condition ass `$o.account == MyConstants.LONG_CFD`
2. Change the super class for all your conditions by setting the `evrete.impl.condition-base-class` configuration parameter. This way, every static declaration in the base class will become immediately available to all literal conditions.


Regarding declaring a custom field, please have a look at this guide: https://evrete.org/guides/howto/field-declaration/

```java
TypeField factorialField = knowledge
        .getTypeResolver()
        .getOrDeclare(Integer.class)
        .declareLongField(
                "factorial",
                i -> {
                    long f = 1L;
                    for (int t = 1; t <= i; t++) f *= t;
                    return f;
                }
        );
```
