### ISSUE TITLE
Can we configure rulesets in evrete using XML configuration instead of JAVA 

### ISSUE THREAD

**Issue by ammu-n15** [evrete/evrete#73]
Is there a way that we can define rulesets and rules in evrete using xml configuration instead of JAVA based.

**Comment by andbi** [comment]
Evrete is a Java rule engine that simplifies the process of creating your own DSL (domain-specific rule language). Simply generate an XML format suitable for your data domain, run the DOM or SAX XML parser, and add rules using the RuleBuilder one by one.

The reason why Evrete doesn't include predefined rule formats like XML or Excel is that there's no way of knowing which format is best for your specific case.

**Comment by ammu-n15** [comment]
@andbi , can we define rules in xml. having the domain data in XML is a different thing.my query is can we have rule builder itself in xml

**Comment by andbi** [comment]
@ammu-n15  I didn't mean the domain data should be in XML. What I meant is a ruleset like this:

```
<ruleset>
    <rule name="Rule 1">
        <facts>
            <fact type="com.example.domain.Customer" name="$c"/>
            <fact type="com.example.domain.Order" name="$o"/>
        </facts>
        <conditions>
            <where criteria="$c.status == 1"/>
            <where criteria="$o.type == 2"/>
        </conditions>
        <action>
            <!-- Java code in CDATA section -->
        </action>
    </rule>
    <rule name = "Rule 2">
        <!-- And so on -->
    </rule>
</ruleset>
```

This is a very general example of a ruleset in XML format. It's very technical and follows the RuleBuilder's structure. But what if your customers, or whoever is going to write these rules, don't know nothing about Java code, correct condition syntax, and so on?

Isn't it better to offer them the XML format they understand and won't make any mistakes?  How about this one:

```
<ruleset>
    <rule name="Shipping Rule">
        <customer name="c"/>
        <order name="o"/>
        <where customer="c" valid="yes"/>
        <where order="o" ready="yes"/>
        <ship what="o" to="c"/>
    </rule>
</ruleset>
```

This implies that developers (like yourself or myself) need to parse this XML file, replace the `ready` flag with actual Java conditions, implement the `ship` action (also in Java), and so on. Which is actually not a big deal, is a win-win for both sides. We, developers, are happy that rule authors don't make mistakes and the app support is minimal. Our customers are happy because XML is simple and self-explanatory.

And, getting back to the original question, there's no way of knowing what's best for your customers. No knowledge, no XML format.

As for incorporating the first XML  into the engine, it isn't worth a shot either. Every developer can parse XML, and they always will end up with XML number 2 which suits their needs better.

Regards,
@andbi

**Comment by ammu-n15** [comment]
@andbi , do we have any sample examples to write the rule builder itself in xml

**Comment by ammu-n15** [comment]
@andbi where do we have this ruleset tags, any documentation for the same

**Comment by andbi** [comment]
I made up that ruleset tag, it's just an example.

How to load, save, and parse XML files (navigate its nodes) is something you'll need to learn on your own, but the general approach is simple:

1. You create a RuleBuilder instance.
2. Next you load the XML file (I recommend DOM parser for starters)
3. Then you navigate the DOM model node by node and, depending on the node, add rules, conditions, or actions to the rule builder you previously initialized.
4. When you get to the end of the XML document, your rule builder will be ready.
